name = "uthgard-herald"
main = "src/index.ts"
compatibility_date = "2025-08-16"

kv_namespaces = [
  { binding = "WARMAP", id = "f485baf327a84b978a15bf681460b72d", preview_id = "b9c02fba4fb04f5cbe35977b77a6a0a3" }
]

[triggers]
crons = ["*/1 * * * *"]

[vars]
HERALD_WARMAP_URL = "https://herald.uthgard.net/herald.php?view=index"
ATTACK_WINDOW_MIN = "7"
MAX_EVENTS = "50"
