name: Daily Scraper

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day at 6:00 UTC
  workflow_dispatch: # Allow manual run from GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Build TypeScript to JS
      - name: Build scraper
        run: npm run build:scraper

      # Run the compiled JS instead of ts-node
      - name: Run scraper
        run: npm run scrape

      # Optional: run aggregation if needed
      - name: Run aggregation
        run: npm run aggregate

      # in .github/workflows/scrape.yml (after aggregate)
      - name: Commit JSON
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/public
          git commit -m "update data [skip ci]" || echo "no changes"
          git push
